apiVersion: v1
kind: Template
metadata:
  name: solver-buildconfig
  annotations:
    description: >
      This is Thoth Solver Fedora 28+ and UBI8 BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: Solver Fedora 28+ BuildConfig'
    version: 0.7.0
    tags: thoth,ai-stacks,aistacks,solver,machinlearning
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Solver Fedora 28+ and UBI8 BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: solver-buildconfig
    app: thoth
    component: solver

parameters:
  - description: Name of the github repository
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/solver'

  - description: Git reference to be used
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: solver-fedora-29-py37
      labels:
        app: thoth
        component: solver
        app.kubernetes.io/name: "thoth"
        app.kubernetes.io/component: "solver"
        app.thoth-station.ninja/solver: "fedora-29-py37"
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "solver-fedora-29-py37:${IMAGE_STREAM_TAG}"
      source:
        dockerfile: |
          FROM fedora:29
          CMD ["pypi"]
          ENTRYPOINT ["thoth-solver"]
          ENV \
          LANG=en_US.UTF-8 \
          THOTH_SOLVER_TMP_DIR='/tmp/thoth-solver-install'

          RUN \
          useradd -m solver && \
          dnf update --setopt=tsflags=nodocs -y && \
          mkdir -p ${THOTH_SOLVER_TMP_DIR}

          # Install thoth-solver itself
          COPY ./ ${THOTH_SOLVER_TMP_DIR}
          RUN \
          cd ${THOTH_SOLVER_TMP_DIR} &&\
          pip3 install . &&\
          cd / &&\
          rm -rf ${THOTH_SOLVER_TMP_DIR} &&\
          unset THOTH_SOLVER_TMP_DIR &&\
          dnf clean all &&\
          chmod 777 /home/solver

          WORKDIR /home/solver
          USER solver
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      resources:
        limits:
          memory: '512Mi'
          cpu: '500m'
        requests:
          memory: '512Mi'
          cpu: '500m'
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: fedora:29
        type: Docker
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: solver-fedora-29-py36
      labels:
        app: thoth
        component: solver
        app.kubernetes.io/name: "thoth"
        app.kubernetes.io/component: "solver"
        app.thoth-station.ninja/solver: "fedora-29-py36"
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "solver-fedora-29-py36:${IMAGE_STREAM_TAG}"
      source:
        dockerfile: |
          FROM fedora:29
          CMD ["pypi"]
          ENTRYPOINT ["thoth-solver"]
          ENV \
          LANG=en_US.UTF-8 \
          THOTH_SOLVER_TMP_DIR='/tmp/thoth-solver-install'

          RUN \
          useradd -m solver && \
          dnf update --setopt=tsflags=nodocs -y && \
          dnf install --setopt=tsflags=nodocs -y python36 && \
          ln -sf /usr/bin/python3.6 /usr/bin/python3 && \
          mkdir -p ${THOTH_SOLVER_TMP_DIR}

          # Install thoth-solver itself
          COPY ./ ${THOTH_SOLVER_TMP_DIR}
          RUN \
          cd ${THOTH_SOLVER_TMP_DIR} &&\
          pip3 install . &&\
          cd / &&\
          rm -rf ${THOTH_SOLVER_TMP_DIR} &&\
          unset THOTH_SOLVER_TMP_DIR &&\
          dnf clean all &&\
          chmod 777 /home/solver

          WORKDIR /home/solver
          USER solver
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      resources:
        limits:
          memory: '512Mi'
          cpu: '500m'
        requests:
          memory: '512Mi'
          cpu: '500m'
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: fedora:29
        type: Docker
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: solver-fedora-28-py36
      labels:
        app: thoth
        component: solver
        app.kubernetes.io/name: "thoth"
        app.kubernetes.io/component: "solver"
        app.thoth-station.ninja/solver: "fedora-28-py36"
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "solver-fedora-28-py36:${IMAGE_STREAM_TAG}"
      source:
        dockerfile: |
          FROM fedora:28
          CMD ["pypi"]
          ENTRYPOINT ["thoth-solver"]
          ENV \
          LANG=en_US.UTF-8 \
          THOTH_SOLVER_TMP_DIR='/tmp/thoth-solver-install'

          RUN \
          useradd -m solver && \
          dnf update --setopt=tsflags=nodocs -y && \
          mkdir -p ${THOTH_SOLVER_TMP_DIR}

          # Install thoth-solver itself
          COPY ./ ${THOTH_SOLVER_TMP_DIR}
          RUN \
          cd ${THOTH_SOLVER_TMP_DIR} &&\
          pip3 install . &&\
          cd / &&\
          rm -rf ${THOTH_SOLVER_TMP_DIR} &&\
          unset THOTH_SOLVER_TMP_DIR &&\
          dnf clean all &&\
          chmod 777 /home/solver

          WORKDIR /home/solver
          USER solver
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      resources:
        limits:
          memory: '512Mi'
          cpu: '500m'
        requests:
          memory: '512Mi'
          cpu: '500m'
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: fedora:28
        type: Docker
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "solver-ubi-8-py36"
      labels:
        app: "thoth"
        component: "solver"
        app.kubernetes.io/name: "thoth"
        app.kubernetes.io/component: "solver"
        app.thoth-station.ninja/solver: "ubi-8-py36"
    spec:
      output:
        to:
          kind: "ImageStreamTag"
          name: "solver-ubi-8-py36:${IMAGE_STREAM_TAG}"
      source:
        dockerfile: |
          FROM registry.access.redhat.com/ubi8/python-36:1-24

          ENV LANG=en_US.UTF-8 \
              THOTH_SOLVER_TMP_DIR='/tmp/thoth-solver-install'

          USER 0
          RUN useradd -m solver -s /sbin/nologin -c "Thoth Solver User"

          USER ${USERID}
          RUN mkdir -p ${THOTH_SOLVER_TMP_DIR}

          # Install thoth-solver itself
          COPY ./ ${THOTH_SOLVER_TMP_DIR}
          RUN cd ${THOTH_SOLVER_TMP_DIR} &&\
              pip3 install . &&\
              cd / &&\
              rm -rf ${THOTH_SOLVER_TMP_DIR} &&\
              unset THOTH_SOLVER_TMP_DIR

          WORKDIR /home/solver
          USER solver

          CMD ["pypi"]
          ENTRYPOINT ["thoth-solver"]
        type: Git
        git:
          uri: "${GITHUB_URL}"
          ref: "${GITHUB_REF}"
      resources:
        limits:
          memory: '512Mi'
          cpu: '500m'
        requests:
          memory: '512Mi'
          cpu: '500m'
      strategy:
        type: "Docker"
        dockerStrategy:
          from:
            kind: "ImageStreamTag"
            name: "python-36:latest"
      triggers:
        - type: "ImageChange"
          imageChange: {}
